routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// -- Authentication Routes
Auth::routes();

// -- BEGIN -- public routes
Route::get('/', function () {
    return view('welcome');
});

Route::get('logout', function () {
    Auth::logout();
    session()->flush();
    return redirect('/');
});

Route::get('home', function () {
    return redirect()->route('dashboard.index');
});
// -- END -- Public routes

// Set Locale
App::setLocale('en');

// -- BEGIN -- Model binding
    // Route::model('module', App\Module::class);
// -- END -- Model binding

// -- BEGIN -- Private route
Route::group(['middleware' => ['auth', 'roleAuth']], function () {
    // -- BEGIN -- Resource route
    Route::resource('dashboard', 'DashboardController');
    Route::resource('modules', 'ModulesController');
    Route::resource('users', 'UsersController', ['except' => ['show']]);
    Route::resource('staffs', 'StaffsController');
    Route::resource('rolegroups', 'RolegroupsController', ['except' => ['show']]);

    Route::resource('courses', 'CoursesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('exams', 'ExamsController');
    Route::resource('resources', 'ResourcesController');
    Route::resource('groups', 'GroupsController');

    // -- BEGIN -- Datatables Specific
    Route::group(['prefix' => 'datatables'], function () {
        Route::post('modules', 'ModulesController@getDatatablesResources')
            ->name('modules.datatables');
        Route::post('users', 'UsersController@getDatatablesResources')
            ->name('users.datatables');
        Route::post('staffs', 'StaffsController@getDatatablesResources')
            ->name('staffs.datatables');
        Route::post('rolegroups', 'RolegroupsController@getDatatablesResources')
            ->name('rolegroups.datatables');

        Route::post('courses', 'CoursesController@getDatatablesResources')
            ->name('courses.datatables');
        Route::post('tasks', 'TasksController@getDatatablesResources')
            ->name('tasks.datatables');
        Route::post('exams', 'ExamsController@getDatatablesResources')
            ->name('exams.datatables');
    });
    // -- END -- Datatables Specific

    // -- BEGIN -- Other API Router
    Route::post('rolegroups/add_modules/{id}', 'RolegroupsController@addModules')
        ->name('rolegroups.addModules');
    Route::post('rolegroups/remove_modules/{id}', 'RolegroupsController@removeModules')
        ->name('rolegroups.removeModules');
    // -- END -- Other API Router
});
// -- END -- Model binding

app/Course.php
<?php

namespace App;

// use Illuminate\Database\Eloquent\Model;
use App\BaseModel as Model;

class Course extends Model
{
    protected $guarded = [];

    public $route = 'courses';

    public function user()
    {
        return $this->hasOne('\App\User');
    }

    public function tasks()
    {
        return $this->hasMany('\App\Task');
    }

    public function exams()
    {
        return $this->hasMany('\App\Exam');
    }

    public function getTimeRangeAttribute()
    {
        $start = new \Carbon\Carbon($this->time);
        $end = (new \Carbon\Carbon($this->time))->modify("+ ".$this->duration." min");
        return $start->format('H:i')." - ".$end->format('H:i');
    }
}

app/Task.php
<?php

namespace App;

use App\BaseModel as Model;

class Task extends Model
{
    protected $guarded = [];

    public $timestamps = true;

    public $route = 'tasks';

    protected $dates = [
        'deadline',
        'created_at',
        'updated_at',
    ];

    public function course()
    {
        return $this->belongsTo('App\Course');
    }

    public function getCompleteStatusAttribute()
    {
        $now = \Carbon\Carbon::now();
        $then = $this->deadline;
        $diff = $then->diff($now);

        if ($now < $then) {
            $time = " to go";
        } else {
            $time = " past";
        }
        $format = "<span class='label label-%s'>%s</span>";

        if ($this->status == '1') {
            $status = sprintf($format, 'success', 'Completed');
        } else {
            if ($now > $then) {
                $status = sprintf($format, 'danger', 'Uncompleted');
            } else {
                $status = sprintf($format, 'warning', 'Uncompleted');
            }
        }


        return $diff->format('%a days').$time." ".$status;
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $time = \Carbon\Carbon::now('Asia/Jakarta');

        switch ($time->format('H')) {
            case $time < "12":
                $welcome = "Good Morning";
                break;
            case $time >= "12" && $time < "17":
                $welcome = "Good Morning";
                break;
            case $time >= "17" && $time < "19":
                $welcome = "Good Afternoon";
                break;
            case $time >= "19":
                $welcome = "Good Evening";
                break;
            default:
                $welcome = "Hello";
                break;
        }

        $courses = \App\Course::where('user_id', auth()->id())->withCount(['tasks' => function ($task) {
            return $task->where('status', '0');
        }, 'exams'])->with(['tasks', 'exams'])->get();
        $tasks_count = $exams_count = 0;

        $now = \Carbon\Carbon::now('Asia/Jakarta');

        $tasks = $courses->load(['tasks' => function ($task) {
            $now = \Carbon\Carbon::now('Asia/Jakarta');
            // ddr($now->addDay(7));
            return $task->where('status', 0)->where('deadline', '>=', $now->format('Y/m/d'))->where('deadline', '<=', $now->addDay(7)->format('Y/m/d'));
        }, 'tasks.course'])->pluck('tasks')->collapse();

        $exams = $courses->load(['exams' => function ($exam) {
            $now = \Carbon\Carbon::now('Asia/Jakarta');
            return $exam->where('dday', '>=', $now->format('Y/m/d'))->where('dday', '<=', $now->addDay(7)->format('Y/m/d'));
        }])->pluck('exams')->collapse();

        $courses->each(function ($course) use (&$tasks_count, &$exams_count) {
            $tasks_count += $course->tasks_count;
            $exams_count += $course->exams_count;
        });

        return view('dashboard.index')->with([
            'courses' => $courses,
            'tasks' => $tasks,
            'exams' => $exams,
            'today_courses' => $courses->where('day', \Carbon\Carbon::now('Asia/Jakarta')->format('N')),
            'welcome' => $welcome,
            'tasks_count' => $tasks_count,
            'exams_count' => $exams_count,
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard/index.blade.php
@extends('layouts.dashboard')

@section('title', 'PageTitle')

@section('content')
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <h4>
                <span class="text-uppercase">@lang('dashboard.title')</span>
            </h4>
        </div>
    </div>

    <h1>{{ $welcome }}, Fikri.</h1>
    <hr>
    <h4>Here's a list of what you have to do. Have a nice day!</h4>
    <div class="row">
        <div class="col-sm-4">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-pencil-square-o"></i>
                </div>
                <div class="count">{{ $tasks_count }}</div>

                <h3>Uncompleted Tasks</h3>
                <p>from total tasks.</p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="tile-stats">
                <div class="icon"><i class="fa fa-newspaper-o"></i>
                </div>
                <div class="count">{{ $exams_count }}</div>
                <h3>Upcoming Exams</h3>
                <p>from total exams.</p>
            </div>
        </div>
    </div>
    <div class="row" style="margin-left: 0px;">
        <hr>
    </div>
    <div class="row" style="margin-top: 14px;">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>Today's Courses</h2>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <th>Mata Kuliah</th>
                            <th>Jam</th>
                            <th>Ruangan</th>
                        </thead>
                        <tbody>
                            @foreach ($today_courses as $course)
                            <tr>
                                <td>{{ $course->title }}</td>
                                <td>{{ $course->time_range }}</td>
                                <td>{{ $course->room }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>Tasks in 7 days</h2>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <th>Mata Kuliah</th>
                            <th>Status</th>
                        </thead>
                        <tbody>
                            @foreach ($tasks as $task)
                                <tr>
                                    <td>{{ $task->course->title }}</td>
                                    <td>{!! $task->complete_status !!}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2>Exams in 7 days</h2>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <th>Mata Kuliah</th>
                            <th>Tanggal</th>
                        </thead>
                        <tbody>
                            @foreach ($exams as $exam)
                                <tr>
                                    <td>{{ $exam->course->title }}</td>
                                    <td>{{ $exam->dday->format('d-m-Y') }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <hr>
    </div>
</section>
@endsection