routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// -- Authentication Routes
Auth::routes();

// -- BEGIN -- public routes
Route::get('/', function () {
    return view('welcome');
});

Route::get('logout', function () {
    Auth::logout();
    session()->flush();
    return redirect('/');
});

Route::get('home', function () {
    return redirect()->route('dashboard.index');
});
// -- END -- Public routes

// Set Locale
App::setLocale('en');

// -- BEGIN -- Model binding
    // Route::model('module', App\Module::class);
// -- END -- Model binding

// -- BEGIN -- Private route
Route::group(['middleware' => ['auth', 'roleAuth']], function () {
    // -- BEGIN -- Resource route
    Route::resource('dashboard', 'DashboardController');
    Route::resource('modules', 'ModulesController');
    Route::resource('users', 'UsersController', ['except' => ['show']]);
    Route::resource('staffs', 'StaffsController');
    Route::resource('rolegroups', 'RolegroupsController', ['except' => ['show']]);

    Route::resource('courses', 'CoursesController');
    Route::resource('tasks', 'TasksController');
    Route::resource('exams', 'ExamsController');
    Route::resource('resources', 'ResourcesController');
    Route::resource('groups', 'GroupsController');

    // -- BEGIN -- Datatables Specific
    Route::group(['prefix' => 'datatables'], function () {
        Route::post('modules', 'ModulesController@getDatatablesResources')
            ->name('modules.datatables');
        Route::post('users', 'UsersController@getDatatablesResources')
            ->name('users.datatables');
        Route::post('staffs', 'StaffsController@getDatatablesResources')
            ->name('staffs.datatables');
        Route::post('rolegroups', 'RolegroupsController@getDatatablesResources')
            ->name('rolegroups.datatables');

        Route::post('courses', 'CoursesController@getDatatablesResources')
            ->name('courses.datatables');
        Route::post('tasks', 'TasksController@getDatatablesResources')
            ->name('tasks.datatables');
        Route::post('exams', 'ExamsController@getDatatablesResources')
            ->name('exams.datatables');
    });
    // -- END -- Datatables Specific

    // -- BEGIN -- Other API Router
    Route::post('rolegroups/add_modules/{id}', 'RolegroupsController@addModules')
        ->name('rolegroups.addModules');
    Route::post('rolegroups/remove_modules/{id}', 'RolegroupsController@removeModules')
        ->name('rolegroups.removeModules');
    // -- END -- Other API Router
});
// -- END -- Model binding

app/Group.php
<?php

namespace App;

use \App\BaseModel as Model;

class Group extends Model
{
    protected $guarded = [];

    public $timestamps = false;

    public function host()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function members()
    {
        return $this->hasMany('App\User');
    }
}

app/Http/Controllers/GroupsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $group = auth()->user()->group;
        return view('groups.index')->with('group', $group);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->has('action')) {
            if ($request->input('action') == 'join') {
                if (($group = \App\Group::find($request->input('group_id'))) !== null) {
                    \DB::transaction(function () use ($group) {
                        auth()->user()->update(['group_id' => $group->id]);
                    });
                    \Flash::push('success-message', 'You have joined a group');
                } else {
                    \Flash::push('error-message', 'Group didnt exist');
                }
            }
            return back();
        }

        \DB::transaction(function () use ($request) {
            $group = \App\Group::create([
                'name' => $request->input('name'),
                'user_id' => auth()->id()
                ]);

            auth()->user()->update(['group_id' => $group->id]);
        });

        \Flash::push('success-message', 'You have created group');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/groups/index.blade.php
@extends('layouts.dashboard')

@section('title', 'PageTitle')

@section('content')
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <h4>
                <span class="text-uppercase">Groups</span>
            </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
        @if ($group === null)
            <h3>You didnt join any group</h3>
            <button class="btn btn-dark" data-toggle="modal"  data-target="#createGroup">Create Group</button>
            <button class="btn btn-success" data-toggle="modal"  data-target="#joinGroup">Join Group</button>
        @else
            <h3>{{ $group->name }}</h3>
            <h4>Invite ID: {{ $group->id }}</h4>
            <button class="btn btn-danger" data-toggle="modal"  data-target="#joinGroup">Leave Group</button>

            <h4>Host</h4>
            <h5>{{ $group->host->staff->name }}</h5>
            <h4>Members</h4>
            <ul class="list-group">
                @foreach ($group->members as $member)
                    <li class="list-group-item">{{ $member->staff->name }}</li>
                @endforeach
            </ul>
        @endif
        </div>
    </div>
</section>

<!-- Modal -->
<div class="modal fade" id="joinGroup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        {!! Form::open(['url' => route('groups.store', ['action' => 'join'])]) !!}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Join Group</h4>
            </div>
            <div class="modal-body">
                {!! Form::text('group_id', null, ['class' => "form-control", 'placeholder' => "Invite ID"]) !!}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Join</button>
            </div>
        {!! Form::close() !!}
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="createGroup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        {!! Form::open(['url' => route('groups.store')]) !!}
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Join Group</h4>
            </div>
            <div class="modal-body">
                {!! Form::text('name', null, ['class' => "form-control", 'placeholder' => "Group Name"]) !!}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        {!! Form::close() !!}
        </div>
    </div>
</div>
@endsection